name: '$(Date:yyyyMMdd)$(Rev:.r)-$(BuildID)'
trigger:
  - master
  - release/*

#variables:

pool:
  vmImage: macos-latest

stages:
  - stage: build
    displayName: Build
    jobs:
    - job: Build
      steps:
      - checkout: self
        clean: true
      - task: Cache@2
        inputs:
          key: 'toolscache | "$(Agent.OS)" | tools/scripts/buildcache.sh | vendor/XcodeGen/Package.resolved | vendor/mockolo/Package.resolved'
          path: cache
        displayName: Cache build binaries
      - script: sh tools/scripts/buildcache.sh
        displayName: Copy binaries from cache
      - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          SonarCloud: 'CIBG SonarCloud'
          organization: cibg
          scannerMode: CLI
          configMode: manual
          cliProjectKey: 'MSS_iOS'
          cliSources: /Users/runner/work/1/s/
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin     
            sonar.c.file.suffixes=-
            sonar.cpp.file.suffixes=-
            sonar.objc.file.suffixes=-
            sonar.exclusions=vendor/**/*
      - template: build.yml
        parameters:
          networkConfiguration: Test
          logLevel: debug
          bundleShortVersion: tst
          bundleDisplayName: "üêû CoronaMelder"
          debugMenu: true
          runTests: true
          signingOption: 'nosign'
      - script: sh tools/scripts/buildcache.sh copy
        displayName: Copy binaries to cache
      - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
        displayName: 'Run Code Analysis'
      - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
        displayName: 'Publish Quality Gate Result'
      # Run distribution on the master and release/ branches only          
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
        - template: distribute.yml